# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: borales/actions-yarn@v2.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cmd: install

      - name: Use Node.js ${{ matrix.node-version }}
        uses: borales/actions-yarn@v2.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cmd: build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: borales/actions-yarn@v2.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cmd: lint

      - name: Use Node.js ${{ matrix.node-version }}
        uses: borales/actions-yarn@v2.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cmd: test

        env:
          CI: true
